version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    # volumes:
      # - ./app:/app
    command: >
      sh -c "python3 manage.py wait_for_db &&
             python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env-docker
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    env_file:
      - ./.env-docker
    volumes: 
      - validatr-db:/var/lib/postgresql/data

  redis:
    image: redis:alpine

  celery:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A validatr worker -l info
    # volumes:
    #   - ./app:/app
    env_file:
      - ./.env-docker
    depends_on:
      - postgres
      - redis
      - app
volumes:
  validatr-db:
