# Generated by Django 4.1.1 on 2022-09-22 22:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("path", models.TextField()),
                (
                    "provider",
                    models.CharField(
                        choices=[("local", "local")], default=0, max_length=16
                    ),
                ),
                ("start_webhook_endpoint", models.URLField(blank=True, null=True)),
                ("success_webhook_endpoint", models.URLField(blank=True, null=True)),
                ("failure_webhook_endpoint", models.URLField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "queued"),
                            ("in_progress", "in_progress"),
                            ("complete", "complete"),
                            ("failed", "failed"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("errors", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
