# Generated by Django 4.1.1 on 2022-09-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_asset_errors_alter_asset_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="failure_webhook_endpoint",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="start_webhook_endpoint",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="success_webhook_endpoint",
            field=models.TextField(blank=True, null=True),
        ),
    ]
